[package]
name = "bft"
version = "0.1.0"
authors = ["Robin Brown"]
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
crossterm = "0.29.0"
grid = "0.16.1"
rand = "0.9.0"
thiserror = "2.0.12"
